### ISSUE TITLE
Nullability annotations

### ISSUE THREAD

**Issue by pointum** [shpakovski/MASShortcut#102]
Is it OK to make pull requests with nullability annotations? I was going to add some, but I don't know if you intend to support anything below Xcode 7.

**Comment by zoul** [comment]
Three years later, ehm 😇 Yes, we would love the nullability annotations if you’re still interested.

**Comment by zoul** [comment]
Basic annotations have been added, so I’m closing this. If someone needs more of the annotations, feel free to reopen.
