### ISSUE TITLE
shortcut repeat

### ISSUE THREAD

**Issue by kimaldis** [shpakovski/MASShortcut#118]
I don't suppose there's a way to have shortcut keys repeat?

**Comment by shpakovski** [comment]
Not sire what you mean, sorry. Could you please be more specific?

**Comment by kimaldis** [comment]
Sorry, I was unclear. When you key a shortcut key combination and hold it down it doesn't repeat like normal character keys do. I'm using shortcuts to control sliders; one for increase, the other to decrease the slider value. At the moment I have to repeatedly press the key combination. It would be nice if it repeated when held down.

**Comment by shpakovski** [comment]
Ah, I see… This feature is not supported, unfortunately. Sorry for inconvenience 😐

**Comment by kimaldis** [comment]
No problem. It was just a thought
