### ISSUE TITLE
Possibility to bind shortcuts application-specific instead of globally?

### ISSUE THREAD

**Issue by JoeriBultheel** [shpakovski/MASShortcut#122]
Hi, 

I love MASShortcut, but I want to have one of my shortcuts to not be active system-wide/globally but only when my app is in focus. Is there a possibility to set this in code somehow?

Thank you

**Comment by shpakovski** [comment]
Hi Joeri, please check this API: [addLocalMonitorForEvents(matching:handler:)](https://developer.apple.com/documentation/appkit/nsevent/1534971-addlocalmonitorforevents). Does it help?

**Comment by JoeriBultheel** [comment]
Thank you! 

I only knew about addGlobalMonitor... silly me.
Would be nice to integrate this into MASShortcuts nonetheless imo.

Cheers

**Comment by zoul** [comment]
If I understand the issue correctly, adding a local handler for a `MASShortcut` should be fairly easy using the API linked to above, so I don’t feel like this is a must have in MASShortcut. Joeri, if you have a use case where additional support in MASShortcut would make life much easier for you, please reopen. Thank you!
