### ISSUE TITLE
Add keyEquivalent to NSMenuItem

### ISSUE THREAD

**Issue by corysullivan** [shpakovski/MASShortcut#133]
I'm attempting to add a keyEquivalent to an NSMenuItem that corresponds to a particular `MASShortcut`. However, the only way I can get this value is through the `MASShortcutView` 

```
shortcutView.shortcutValue.keyCodeStringForKeyEquivalent
```
is it possible to get a reference to the shortcut any other way?

**Comment by zoul** [comment]
I’m not sure if I follow. There’s a `keyCodeStringForKeyEquivalent` property on `MASShortcut`. What keeps you from using that, directly? I’m sorry if I’m missing the point.

**Comment by corysullivan** [comment]
Sure I can use it directly, but the shortcut is initiated in the preference controller, and I was hoping to access it elsewhere, but I can make it work. Thanks
