### ISSUE TITLE
Improve “revert to previous shortcut” icon?

### ISSUE THREAD

**Issue by zoul** [shpakovski/MASShortcut#135]
The icon we currently use for reverting to previously set shortcut is a bit non-intuitive:

![current](https://user-images.githubusercontent.com/95329/59432435-98adce80-8de7-11e9-84b5-f8298123f280.png)

I wonder if we could switch to something like this:

![normal](https://user-images.githubusercontent.com/95329/59432465-a400fa00-8de7-11e9-8234-02cc35680fe3.png)

What do you think, Vadim?

**Comment by shpakovski** [comment]
Hey Tom, I used a standard Escape glyph as a hint too 😄 I like your suggestion but the implementation is not very polished, sorry 🙈

**Comment by zoul** [comment]
100 % agreed :–) I have noticed that the current glyph is the standard one for Escape, but my opinion is that people don’t know it, since it isn’t used much. (I think I only know it from the _Force Quit_ system menu item.) And the glyph I’m proposing is a nice one:

![Screenshot 2019-06-13 at 15 08 25](https://user-images.githubusercontent.com/95329/59435068-1d4f1b80-8ded-11e9-9edd-30c498c3e1ea.png)

…but what the system rendering does to it at this size is inexcusable 😈 I have tried other arrows, too, but none of them work really:

![undo](https://user-images.githubusercontent.com/95329/59435105-2e982800-8ded-11e9-995f-60671e5aa1b7.png)

Do you have some other nice Unicode glyph tips? If not, then let’s leave the current glyph in place.

**Comment by shpakovski** [comment]
Indeed others are even worth, I see now. Thanks. Let’s just leave the current one? 🙈
