### ISSUE TITLE
Can I add a Package.swift file and use it with SPM?

### ISSUE THREAD

**Issue by rampatra** [shpakovski/MASShortcut#144]
I was thinking to add a Package.swift file like below:
```
// swift-tools-version:5.0
import PackageDescription

let package = Package(
    name: "MASShortcut",
    products: [
        .library(name: "Framework",
                 targets: ["Framework"])
    ],
    targets: [
        .target(name: "Framework",
                path: "Framework")
    ]
)
```
and then use it in my swift project. Can I do it?

**Comment by rampatra** [comment]
I actually went ahead and tried the above and I successfully added this library as a dependency but I tried to build it I got the below errors:
<img width="1151" alt="Screenshot 2020-04-17 at 22 21 33" src="https://user-images.githubusercontent.com/2862724/79615318-64d3c180-80fa-11ea-9775-bcec1bf9af31.png">
Any ideas?

_I am a complete greenhorn in swift so please pardon my naivety._

**Comment by rampatra** [comment]
The swift forum helped me [here](https://forums.swift.org/t/can-i-use-swift-package-manager-in-obj-c-code/35463/9?u=rampatra) but the library is behaving weirdly even though it compiles fine. Not sure what's going on. Any help would be really appreciated.

**Comment by shpakovski** [comment]
Hi @rampatra Thanks for trying to wrap this code into a Swift Package. I cannot add an official full-featured package at the moment, but you’re moving in the right direction. Maybe `xxx` is displayed because localization tables are not available. Make sure to copy `.strings` into the main app’s `Resources`. Hope this helps, and sorry for the slow reply!

**Comment by rampatra** [comment]
No worries. I have currently gone with https://github.com/soffes/HotKey for now but I would be soon using this library after I've added a couple of urgent features in the app. I can update here once I am done.

**Comment by iSapozhnik** [comment]
@rampatra @shpakovski 
I think the problem here is that currently it's not possible to add any resources to SPM.
But it will be possible pretty soon ;)
https://forums.swift.org/t/se-0271-package-manager-resources/30730

**Comment by rampatra** [comment]
@iSapozhnik yes, so I have gone with the below code (in MASLocalization.m file) to allow only English translation for now:
```
return [localizationBundle localizedStringForKey:key
        value:key
        table:MASLocalizationTableName];
```
All credit goes to https://forums.swift.org/t/can-i-use-swift-package-manager-in-obj-c-code/35463/19

**Comment by rampatra** [comment]
I am closing this as I've converted it to a Swift Package successfully [here](https://github.com/rampatra/MASShortcut).

Thanks for all the help!
