### ISSUE TITLE
Unconsistency between italian translation from Apple

### ISSUE THREAD

**Issue by ildede** [shpakovski/MASShortcut#145]
I notice that in the file [it.lproj/Localizable.strings](https://github.com/shpakovski/MASShortcut/blob/master/Resources/it.lproj/Localizable.strings)
is used the word "scorciatia" as translation for "shortcut", but actually Apple use the word "abbreviazione".
The meaning is the same, but I think it's better to keep consistency with Apple style what do you think?

![Screenshot 2020-05-21 at 23 02 48](https://user-images.githubusercontent.com/3754465/82606861-13ff2f00-9bb8-11ea-8b26-5b2db14a16e8.png)
![Schermata 2020-05-21 alle 22 53 29](https://user-images.githubusercontent.com/3754465/82606863-15305c00-9bb8-11ea-8e18-e19805bd8432.png)

It's ok if I'll submit a PR in the next days about this?

**Comment by shpakovski** [comment]
Sure, thanks a ton 🙏

**Comment by Kentzo** [comment]
@ildede would you mind to also check https://github.com/Kentzo/ShortcutRecorder/blob/master/Resources/it.lproj/ShortcutRecorder.strings ?

**Comment by ildede** [comment]
> @ildede would you mind to also check https://github.com/Kentzo/ShortcutRecorder/blob/master/Resources/it.lproj/ShortcutRecorder.strings ?

Yeah sure! There's minor issue there, I will fix those ;)
