### ISSUE TITLE
Layout issue on macOS Big Sur

### ISSUE THREAD

**Issue by GetToSet** [shpakovski/MASShortcut#149]
It seems that macOS Big Sur [added some extra padding](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-11#NSButton) on NSButtons and buttons drawn directly from NSButtonCell has their title stretched out of its bezel, which results bad look of MASShortcutView on macOS Big Sur.

<img width="491" alt="NSButton" src="https://user-images.githubusercontent.com/8158163/92988269-88aa0080-f4fc-11ea-860d-30d10ed207fe.png">

Examples below with bad layout of hint icons displayed outside of its bezel.

<img width="505" alt="截屏2020-09-12 下午1 31 01" src="https://user-images.githubusercontent.com/8158163/92988275-8fd10e80-f4fc-11ea-8282-c6b75040e33e.png">

<img width="505" alt="截屏2020-09-12 下午1 31 23" src="https://user-images.githubusercontent.com/8158163/92988273-8cd61e00-f4fc-11ea-8d46-52db0719d681.png">

**Comment by shpakovski** [comment]
Hey @GetToSet Thanks a lot for the report! Not sure when I will have time to pick this up, so if anyone wants to fix this, you’re kindly welcome.

**Comment by GetToSet** [comment]
This behavior seems more like a bug of macOS. New beta (or perhaps GM) builds may roll out soon. I'll try to fix this problem if it still presents in later builds of macOS.

**Comment by sweetppro** [comment]
I have this mostly fixed, with the exception of rounded button. Once I figure out how to make this one play nicely I’ll add the fix to my SPM pull request.

**Comment by sweetppro** [comment]
fixed in this pull request:
https://github.com/shpakovski/MASShortcut/pull/159
