### ISSUE TITLE
Can't set two arrow keys as part of a shotcut

### ISSUE THREAD

**Issue by ColtonIdle** [shpakovski/MASShortcut#151]
I want to have a shortcut that is ctrl + option + left + up for example but I can only choose a single arrow key. Is this purposeful?

**Comment by Kentzo** [comment]
A macOS “shortcut” may have at most one non-modifier key. 

You may modify the UI component to render that sequence, but will have to intercept such event manually.

Best Regards
Ilya Kulakov

**Comment by shpakovski** [comment]
@Kentzo Thanks for the answer!

@ColtonIdle AppKit doesn’t support multiple non-modifier keys in a single event, so this would be a problem to implement this technically. Sorry for the inconvenience 🤷‍♂️
