### ISSUE TITLE
Add Accessibility Support

### ISSUE THREAD

**Issue by gcox** [shpakovski/MASShortcut#47]
Unfortunately, this control seems to be unusable by voice over users.  I'd love to drop ShortcutRecorder (https://github.com/Kentzo/ShortcutRecorder) and switch to MASShortcut but it isn't an option without accessibility support.

**Comment by aral** [comment]
I love the MASShortcut API but, without accessibility support, I’m going to have to use ShortcutRecorder also. What’s the latest on this? Starkos, have you made any progress? Is there a list of issues outstanding that need to be fixed to enable accessibility support? :)

**Comment by zoul** [comment]
Could somebody who needs the accessibility features create a list of requirements?

**Comment by starkos** [comment]
Yes, I've made progress. I've got a small snag I'm trying to workaround, see http://stackoverflow.com/questions/27925611 <http://stackoverflow.com/questions/27925611>

I will try to commit and push a branch that people can try either later tonight or tomorrow. Some feedback on it would be good.

**Comment by aral** [comment]
That's so cool, thank you. Can’t wait to check it out and will take a look at the issue also :)

Aral

**Comment by starkos** [comment]
Okay, here's the work-in-progress branch: https://github.com/starkos/MASShortcut/tree/issue-47-accessibility

You'll need to be on 10.10 for this version, as I've only implemented the new NSAccessibility API so far. Once things are basically working, I'll wrap them with the legacy calls for older systems.

I worked around the issue I mentioned (see above) by removing the shortcut description from the announcement feedback, so now it just says "Shortcut set". Originally I had it saying "(shortcut description) shortcut set", which I thought was more useful. If you want to try it out, look for "Give VO users feedback on the result" and try appending _shortcutValue.description to the message strings.

**Comment by aral** [comment]
Thank you so much — sorry for the delay in responding; been working on different areas. Will play with this this weekend :) Really appreciate it.
>

**Comment by gcox** [comment]
@starkos Should probably override [NSView acceptsFirstResponder:] to return YES so this control can be tabbed to. Perhaps there's more to it than that but my point is that you can't tab to it currently:)

**Comment by starkos** [comment]
I've enabled first responder on the control—does that help? I'm currently trying to figure out why it doesn't work when placed into an NSTableView.

**Comment by zoul** [comment]
This has been silent for a long time now. I will close the issue and if there any other accessibility related trouble, we can open another one. Thanks for contributing!
