### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by zoul** [shpakovski/MASShortcut#54]
To be done:

* [x] Simplify the demo project to the basic use case
* [x] Add CocoaPods installation instructions
* [x] Add CocoaPods installation instructions for staying on the 1.x branch
* [x] Test CocoaPods installation
* [x] Add a documentation notice for people who would like to migrate from Shortcut Recorder

**Comment by shpakovski** [comment]
Mate, I'm sorry but we cannot simplify the Demo :) It was built on purpose as result of many feature requests, so we really need enable-disable functionality as well as hard-coded shortcut. Please restore, thanks in advance.

**Comment by zoul** [comment]
Allright, sorry! :–) I’ll bring back a nicer demo showing more features.

**Comment by zoul** [comment]
Just pushed 2.0.1 (silly version bump because of Podspec fixes) to CocoaPods.
