### ISSUE TITLE
Fix documentation markup for CocoaDocs

### ISSUE THREAD

**Issue by zoul** [shpakovski/MASShortcut#55]
Looking at the nice documentation generated over at [CocoaDocs](http://cocoadocs.org/docsets/MASShortcut/2.0.1/), the documentation markup used in our source code doesn’t work correctly. There are several ways to mark up the documentation – the current one works in Xcode, but apparently not on CocoaDocs. We should take a look at some other library to see what works for them.

**Comment by shpakovski** [comment]
Something like this works on CocoaPods:

```objective-c
/// Returns custom class for drawing control.
+ (Class)shortcutCellClass;
```

**Comment by zoul** [comment]
Nope, the new version still doesn’t work as expected, all the markup is ignored. Will try with `appledoc` to see if I can find the reason.

**Comment by zoul** [comment]
Yes, now it [finally works](http://cocoadocs.org/docsets/MASShortcut/2.1.1/).
