### ISSUE TITLE
Stop working after registering the same input after cancellation

### ISSUE THREAD

**Issue by noraesae** [shpakovski/MASShortcut#70]
First of all, thanks for this great job. It really saves a whole lot of my time.

I found a bug that a shortcut stops working after registering the same shortcut as before after cancelling it. This occurs in the demo app too.

#### Steps to Reproduce

* Register a shortcut, let me say it's `cmd+j`.
* Cancel the shortcut
* Register the same shortcut, `cmd+j`.
* And then the shortcut stops working.

Is there any documentation I missed or is this a bug?

Thanks in advance.

**Comment by noraesae** [comment]
Just found a workaround like below, but not quite sure if it's rightly done.

```swift
// swift
func shortcutValueDidChanged(sender: MASShortcutView!) {
    if sender.shortcutValue == nil {
        resetShortcutBinder()
    }
}

func resetShortcutBinder() {
    MASShortcutBinder.sharedBinder().breakBindingWithDefaultsKey(shortcutKey!)
    MASShortcutBinder.sharedBinder().bindShortcutWithDefaultsKey(shortcutKey!, toAction: selectInput)
}
```

**Comment by shpakovski** [comment]
@zoul Hey Tom, I'm calling for help 😆

**Comment by zoul** [comment]
I’m currently offline, will take a look at the issue on Sunday or next week. Since the bug is reproducible, it should be easy to fix.

**Comment by Stillness-2** [comment]
I think this #71

**Comment by shpakovski** [comment]
@noraesae Could you please verify the fix? Thanks in advance.

**Comment by noraesae** [comment]
I've tested the patch and it works like a charm. Thanks!

**Comment by shpakovski** [comment]
Thank you all guys!
