### ISSUE TITLE
MASShortcutGlyph needs a `typedef`

### ISSUE THREAD

**Issue by hildjj** [shpakovski/MASShortcut#72]
Suggested:

```
typedef enum {
...
} MASShortcutGlyph;
```

This allows the header file to be included in multiple different places without causing `duplicate symbol _MASShortcutGlyph`.

**Comment by zoul** [comment]
AFAIK this is already fixed in the current master, see dcb1342. Will release a new version today. Thanks!

**Comment by zoul** [comment]
This should be now fixed in 2.2.0. If not, please reopen.

**Comment by anti-transmission** [comment]
Can you fix for 1.0 branch as well? Thank you!
