### ISSUE TITLE
Why don’t we allow shortcuts with Shift and Alt modifiers?

### ISSUE THREAD

**Issue by zoul** [shpakovski/MASShortcut#79]
Recently I have found that MASShortcut doesn’t record shortcuts such as Shift-Alt-U. The reason is in the [validation logic in `MASShortcutValidator`](https://github.com/shpakovski/MASShortcut/blob/master/Framework/MASShortcutValidator.m#L40). I can understand why we disallow Alt-something, but shouldn’t Shift-Alt-something work? @shpakovski, do you have an idea why Shift-Alt-something is not considered valid? Thanks!

**Comment by shpakovski** [comment]
@zoul I did not want to encourage these shortcuts because Shift-Option works just like Option. For example, Shift-Option-K = .

**Comment by zoul** [comment]
Makes sense, thank you! (I will document the behaviour so that people know the thinking behind it.) I noticed the `allowAny…` switch, but I wasn’t sure what the exact deal was, what were the potential drawbacks, so I didn’t touch it. I’ll leave the issue open as a reminder to update the docs.

**Comment by shpakovski** [comment]
Cool, thanks!

**Comment by SenorSamuel** [comment]
that's really cool
