### ISSUE TITLE
German localization strings don’t fit the recording control

### ISSUE THREAD

**Issue by zoul** [shpakovski/MASShortcut#85]
@floschliep, the new German strings you have contributed in the [last pull request](https://github.com/shpakovski/MASShortcut/pull/84) are too long to fit the control. I have introduced some basic support for the German localization to the demo project, can you please run it in German and take a look? As an example, the _Neuen Kurzbefehl eingeben_ “tip” displayed in the recording area is clipped. Is it possible to shorten the string? Thanks!

**Comment by floschliep** [comment]
I can shorten the strings, but the shorter the less descriptive they are. Here're the different versions:

Original  |  Long  |  Medium  |  Short
----------- | --------  |  -----------  |  --------
Type New Shortcut  |  Neuen Kurzbefehl eingeben  |  Neuen Befehl eingeben  |  Neuen eingeben
Use Old Shortcut  |  Alten Kurzbefehl nutzen  |  Alten Befehl nutzen  |  Alten nutzen

**Comment by zoul** [comment]
I am afraid only the shortest ones will fit. If they are acceptable, I’d stick with them, for I can’t see any other easy way out.
