### ISSUE TITLE
MASShortcut/MASShortcut.bundle: No such file or directory

### ISSUE THREAD

**Issue by jhoughjr** [shpakovski/MASShortcut#88]
Trying to build with cocoapods. When i did a pod update, I ran into this build error.
I'm not sure how to fix it, since i don't see the bundle it is looking for anywhere under the pods project.

**Comment by jhoughjr** [comment]
Inside of derived data ../Debug/ I have MASShortcut, and another MASShortcut folder that contains the bundle.
When i manually moved it out into the top level of MASShortcut, the same level with the framework it built.

**Comment by zoul** [comment]
Just a week ago we were investigating a different issue regarding CocoaPods (see #87) and I tried building a fresh Xcode project with the current MASShortcut version installed through CocoaPods, with no problems. Can you please make sure that it’s not a local problem with CocoaPods? Maybe reinstall the pods afresh?

**Comment by jhoughjr** [comment]
I've tried reinstalling cocoa pods and am at 0.39.0.
I deleted the xcworkspace and did pod install.

I'm still getting : 
CpResource /Users/jimmyhoughjr/Library/Developer/Xcode/DerivedData/GhostNote-aqfthowqdbdibwensghrcgbcparn/Build/Products/Debug/MASShortcut/MASShortcut.bundle /Users/jimmyhoughjr/Library/Developer/Xcode/DerivedData/GhostNote-aqfthowqdbdibwensghrcgbcparn/Build/Products/Debug/MASShortcut/MASShortcut.framework/Versions/A/Resources/MASShortcut.bundle
    cd /Users/jimmyhoughjr/workspace/ghostnote-Paddle/Pods
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/jimmyhoughjr/Library/Developer/Xcode/DerivedData/GhostNote-aqfthowqdbdibwensghrcgbcparn/Build/Products/Debug/MASShortcut/MASShortcut.bundle /Users/jimmyhoughjr/Library/Developer/Xcode/DerivedData/GhostNote-aqfthowqdbdibwensghrcgbcparn/Build/Products/Debug/MASShortcut/MASShortcut.framework/Versions/A/Resources

error: /Users/jimmyhoughjr/Library/Developer/Xcode/DerivedData/GhostNote-aqfthowqdbdibwensghrcgbcparn/Build/Products/Debug/MASShortcut/MASShortcut.bundle: No such file or directory

This built before i did a pod update a few days ago, and idk what is going on.

**Comment by jhoughjr** [comment]
Seems I needed to fully uninstall all versions, i had a few.
Reinstalling and remaking the workspace appears to have fixed it.

**Comment by jhoughjr** [comment]
BTW thanks for the suggestion!
