### ISSUE TITLE
Format the Option modifier as “alt”, not ⌥

### ISSUE THREAD

**Issue by zoul** [shpakovski/MASShortcut#96]
Apple has dropped the ⌥ symbol from (some? all?) recent keyboards:

![modern Apple keyboard](https://cloud.githubusercontent.com/assets/95329/18831597/d50d2b36-83e6-11e6-86b2-e700dbb7e81d.jpeg)

Which means we are formatting the Option key in a way that can be confusing for some users, since they can’t find the ⌥ key on their keyboards. Note that this problem also applies to Apple themselves, since macOS keeps using the ⌥ symbol in menus.

I suggest that we use the “alt” string instead, because that’s present both on the older and the newest keyboard models. In other words, format Option-K as “alt-K”, not “⌥K”.

@shpakovski, what do you think?

**Comment by shpakovski** [comment]
Hi Tom! Ugh, this is so controversial… Let’s wait while Apple releases new MacBook Pro? 😃

**Comment by zoul** [comment]
The trouble is that an app can tell you to press something like ⌥K when there’s no such key as ⌥ on your keyboard. And you’re right – Control is the same problem.

We went through an internal discussion for an app we use MASShortcut for and decided to leave the code as it is, at least for the moment, because the current behaviour is consistent with the system. Which is the most important thing.

So I’m closing the issue – but still, having to explain your users why you use symbols that aren’t on their keyboards sucks.
