### ISSUE TITLE
Silence deprecation warnings when building for Sierra

### ISSUE THREAD

**Issue by zoul** [shpakovski/MASShortcut#99]
See #98 for the rationale.

**Comment by zoul** [comment]
Long story short: `NSControlKeyMask` and friends were replaced with `NSEventModifierFlagControl` and similar in macOS Sierra. The project builds fine & clean, but including MASShortcut in a project with deployment target set to 10.12 results in several deprecation warnings because of the control masks. Simply replacing the old symbols with the new ones isn’t an option, since it breaks the build on older SDKs – in Travis, for example.

**Comment by zoul** [comment]
[Here’s a similar scenario](https://lists.gnu.org/archive/html/emacs-devel/2016-08/msg00358.html), they simply define the new symbols on older SDKs. I think that’s an acceptable approach if we get the SDK version check right. We could then delete the defines later, when 10.12 is the standard SDK everywhere.

**Comment by zoul** [comment]
OK, after a few fumbles I think I got the conditional defines right. @clemens-schulz, can you please verify that the current HEAD builds cleanly in your 10.12 project? After that I can make a release.

**Comment by clemens-schulz** [comment]
Current HEAD builds cleanly. 👍 Thank you for fixing it!

**Comment by zoul** [comment]
Great, happy to help. Now available in the 2.3.6 release.
